 // imports the HtmlWebpackPlugin, a plugin for Webpack that simplifies the creation of HTML files to serve your bundled JavaScript files.
const HtmlWebpackPlugin = require('html-webpack-plugin');
// imports the CopyPlugin, another Webpack plugin that allows you to copy individual files or entire directories from one location to another in your build process. 
const CopyPlugin = require('copy-webpack-plugin');
// imports Node.js's built-in path module, which provides utilities for working with file and directory paths.
const path = require('path');

module.exports = {
  // mode: create a build that is optimized for development purposes, allowing for improved debugging and faster builds at the cost of output size and performance 
  // optimizations that would be present in production mode. Production mode is default
  mode: 'development',
  // source index.js file. Webpack will begin bundling from this JavaScript file.
  entry: './src/index.js',
  // defines how and where to output the bundled files generated by Webpack
  output: {
    // the output directory for the bundled files. --dirname is the directory where your Webpack configuration file resides
    path: path.resolve(__dirname, 'dist'),
    // name of the output bundle file
    filename: 'app.js',
  },
  plugins: [
    // HtmlWebpackPlugin enable Webpack to automatically generate an HTML file that includes references to all your bundled JavaScript and CSS files. 
    // Output is in path: path.resolve(__dirname, 'dist'),
    new HtmlWebpackPlugin(
      { // path to an HTML file that will serve as a template for generating the final HTML file
        template: './src/index.html', 
      }
    ),
    new CopyPlugin(
      {
        // pattern is array that specifies the files or directories to copy and their respective destinations  
        patterns: [
          // pattern tells webpack to copy styles.css to dist/css folder
          { from: './src/style.css', to: 'css' }
        ]
      }
    ),
  ],
};